routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Auth::routes();

Route::group(['middleware' => 'auth'], function () {

	Route::get('/', 'HomeController@index')->name('index');

	Route::resource('/album', 'AlbumController');

	Route::resource('/photo', 'PhotoController');

	Route::get('/profile', 'ProfileController@edit')->name('profile');

	Route::post('/profile', 'ProfileController@update')->name('profile.update');

	Route::delete('/profile', 'ProfileController@destroy')->name('profile.destroy');
	
});


Route::resource('/users', 'UserController');




Route::get('/about', function(){
	return view('about');
})->name('about');

resources/views/about.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="jumbotron jumbotron-sm">
        <div class="row">
            <div class="col-sm-12 col-lg-12 col-xs-12 col-md-12">
                <h1 class="h2">
                    About me
                </h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-xs-12 col-md-6">
            <div class="well">
                <h3 style=""><i class="fa fa-home fa-1x"></i> Adress:</h3>               
                <p>Baltupio 45, Vilnius</p>
                <br />
                <br />
                <h3><i class="fa fa-envelope fa-1x"></i> E-Mail adress:</h3>
                <p style=>tomaskrizanauskas@gmail.com</p>
                <br />
                <br />
                <h3><i class="fa fa-user fa-1x"></i> Tomas Krizanauskas:</h3>
                <p>WEB solutions</p>
                <br />
                <br />
                <h3><i class="fa fa-yelp fa-1x"></i> WEB page:</h3>
                <p><a href="www.tomaskrizanauskas.lt">www.tomaskrizanauskas.lt</a></p>
            </div>
        </div>
        <div class="col-sm-6 col-xs-12 col-md-6">
            <iframe width="100%" height="460" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=baltupio%2045&key=AIzaSyAgheCtCywwQtQ-CShkXzZCg-iw117FX34" allowfullscreen></iframe>
        </div>
    </div>
</div>

@endsection

resources/views/createAlbum.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	
	<div class="row">
		@if (count($errors) > 0)
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
		@endif

		<h3>{{ isset($album) ? 'Edit Album' : 'Add a new Album' }}</h3>

		@if(isset($album))
		{{ Form::open(['route' => ["album.update", $album->id], 'method' => 'POST'] ) }}
		{{ Form::hidden('_method', 'PUT') }}
		
		@else
		{{ Form::open(['route' => ["album.store"], 'method' => 'POST']) }}
		@endif

		{{ Form::label('title', 'Album name:')}}
		{{ Form::text('title', isset($album->title)?$album->title:'', ['class'=>'form-control']) }}

		{{ form::submit(isset($album) ? 'Edit Album' : 'Add new album', ['class'=>'btn btn-primary spacebtn']) }}
		{{ Form::close() }}

		@if(isset($album))
		{{ Form::open(['route' => ['album.destroy', $album->id], 'method' => 'POST']) }}

		{{ Form::hidden('_method', 'DELETE') }}
		{{ form::submit('Delete', ['class'=>'btn btn-danger ']) }}

		{{ Form::close() }}
		@endif

	</div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
	<div class="row ">

		<div class="col-md-3">
			<p class="lead">Wellcome to my photo album :)</p>
			<div class="list-group">
			@if(auth::check() && auth::user()->is_admin)
				<a href="{{ route('album.create') }}" class="list-group-item">Add a new album</a>
				@endif
			@foreach ($albums as $album) 
				<a href="{{ route('album.show', $album->id) }}" class="list-group-item">{{ $album->title }}</a>

			@endforeach
			
			</div>
		</div>
		<div class="col-md-9">

			@foreach ($albums as $album)  

			<div class="row">
				<div class="blockh">
				<div class="inner">
				<h2><a href="{{ route('album.show', $album->id) }}">{{ $album->title }}</a></h2>
				@if(auth::check() && auth::user()->is_admin)
				<a href="{{ route('photo.create')}}?id={{$album->id}}">Add a new photo</a>
				<a href ="{{ route('album.edit', $album->id) }}">( Edit )</a>
				@endif
				</div>
				</div>
			</div>
			<div class="row">
				@foreach($album->photos->take(3) as $index => $photo)

				<div class="col-sm-4 col-lg-4 col-md-4">
					<div class="photo">
						<div class="photo-img">
							<a href="{{ route('photo.show', $photo->id)}}"><img class="img img-responsive" src="{{ url($photo->photo) }}"></a>
						</div>
						<div class="photo-info">
						@if(auth::check() && auth::user()->is_admin)
							<h4 class="pull-right"><a class="btn btn-default" href="{{ route('photo.edit', $photo->id)}}">Edit</a></h4>
						@endif
							<h4 class="title"><a href="{{ route('photo.show', $photo->id)}}">{{ $photo->title }}</a>
							</h4>
							<p><i>{{ mb_strimwidth($photo->description, 0, 150, '...') }}</i></p>
						</div>
					</div>
				</div>
				@endforeach
			</div>
			@endforeach
		</div>

	</div>
	
</div>

@endsection

resources/views/photoSlide.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
    
    <div class="row carousel-holder">

        <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="slide-image" src="{{ url($image->photo) }}" alt="">
                    </div>
                    @foreach($photos as $photo)
                        <div class="item">
                            <img class="slide-image img-responsive" src="{{ url($photo->photo) }}" alt="{{ $photo->title }}">
                        </div>
                    @endforeach
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

    </div>
</div>
@endsection

resources/views/showAlbum.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
	<div class="row ">

		
		<h3>{{ $album_name->title }} </h3>
		@if(auth::check() && auth::user()->is_admin)
		<div class="inner pb">
			<a href="{{ route('photo.create')}}?id={{$album_name->id}}">Add a new photo</a>
			<a href ="{{ route('album.edit', $album_name->id) }}">( Edit )</a>
		</div>
		@endif
			

	</div>
	
		
	<div class="row">
		@foreach($photos as $i => $photo)

		<div class="col-sm-4 col-lg-4 col-md-4">
			<div class="photo">
				<div class="photo-img">
					<a href="{{ route('photo.show', $photo->id)}}"><img class="img img-responsive" src="{{ url($photo->photo) }}"></a>
				</div>
				<div class="photo-info">
				@if(auth::check() && auth::user()->is_admin)
					<h4 class="pull-right"><a class="btn btn-default" href="{{ route('photo.edit', $photo->id)}}">Edit</a></h4>
				@endif
					<h4 class="title"><a href="{{ route('photo.show', $photo->id)}}">{{ $photo->title }}</a>
					</h4>
					<p><i>{{ mb_strimwidth($photo->description, 0, 150, '...') }}</i></p>
				</div>
			</div>
		</div>
		@if(++$i % 3 == 0)
            </div><div class="row">
        @endif
		@endforeach
	</div>
	
</div>

resources/views/upload.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	
	<div class="row">
		@if (count($errors) > 0)
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
		@endif

		<h3>{{ isset($photo) ? 'Edit Photo' : 'Add a new photo' }}</h3>

		@if(isset($photo))
		{{ Form::open(['route' => ["photo.update", $photo->id], 'method' => 'POST', 'files' => true] ) }}
		{{ Form::hidden('_method', 'PUT') }}
		
		@else
		{{ Form::open(['route' => ["photo.store"], 'method' => 'POST', 'files' => true]) }}
		@endif

		{{ Form::label('title', 'Photo title:')}}
		{{ Form::text('title', isset($photo->title)?$photo->title:'', ['class'=>'form-control']) }}

		{{ Form::label('title', 'Paveiksliukas:')}}
		{{ Form::file('photo', ['class'=>'form-control']) }}


		{{ Form::label('album', 'Album:')}}

		
		{{Form::select('album_id', $selectAlbums, isset($photo->album_id)?$photo->album_id:$album_id, ['class'=>'form-control']) }}
		


		{{ Form::label('description', 'Photo description:')}}
		{{ Form::textarea('description',isset($photo->description)?$photo->description:'', ['class'=>'form-control', 'rows' => '10', 'cols' => '30']) }}

		{{ form::submit(isset($photo) ? 'Edit Photo' : 'Add new photo', ['class'=>'btn btn-primary spacebtn']) }}
		{{ Form::close() }}

		@if(isset($photo))
		{{ Form::open(['route' => ['photo.destroy', $photo->id], 'method' => 'POST']) }}

		{{ Form::hidden('_method', 'DELETE') }}
		{{ form::submit('Delete', ['class'=>'btn btn-danger']) }}

		{{ Form::close() }}
		@endif

	</div>
</div>
@endsection

resources/views/userEdit.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	
	<div class="row">

		<h3>Edit user</h3>

		@if (count($errors) > 0)
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
		@endif

		{{ Form::open(['route' => ["users.update", $user->id], 'method' => 'POST']) }}
		{{ Form::hidden('_method', 'PUT') }}

		{{ Form::label('name', 'Name :')}}
		{{ Form::text('name', $user->name, ['class'=>'form-control']) }}
		{{ Form::label('email', 'Email :') }}
		{{ Form::text('email', $user->email, ['class'=>'form-control']) }}
		{{ Form::label('password', 'password :') }}
		{{ Form::text('password', '', ['class'=>'form-control']) }}
		{{ Form::label('is_admin', 'is admin ?') }}
		{{ Form::hidden('is_admin', '0') }}
		{{ Form::checkbox('is_admin', '1', $user->is_admin ) }}

		{{ form::submit('Edit User', ['class'=>'btn block btn-primary  spacebtn']) }}
		{{ Form::close() }}
		


		{{ Form::open(['route' => ['users.destroy', $user->id], 'method' => 'POST']) }}

		{{ Form::hidden('_method', 'DELETE') }}
		{{ form::submit('Delete', ['class'=>'btn btn-danger']) }}

		{{ Form::close() }}



	</div>
	</div>
@endsection

resources/views/userProfile.blade.php
@extends("layouts.app")
@section("content")

<div class="container">
	
	<div class="row">

		<h3>Edit user</h3>
		@if (count($errors) > 0)
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
		@endif

		{{ Form::open(['route' => ["profile.update"], 'method' => 'POST']) }}
		<!-- {{ Form::hidden('_method', 'PUT') }} -->

		{{ Form::label('name', 'Name :')}}
		{{ Form::text('name', $user->name, ['class'=>'form-control']) }}
		{{ Form::label('email', 'Email :') }}
		{{ Form::text('email', $user->email, ['class'=>'form-control']) }}
		{{ Form::label('password', 'password :') }}
		{{ Form::text('password', '', ['class'=>'form-control']) }}
		

		{{ form::submit('Edit User', ['class'=>'btn block btn-primary  spacebtn']) }}
		{{ Form::close() }}
		


		{{ Form::open(['route' => ['profile.destroy'], 'method' => 'POST']) }}

		{{ Form::hidden('_method', 'DELETE') }}
		{{ form::submit('Unregister', ['class'=>'btn btn-danger']) }}

		{{ Form::close() }}



	</div>
</div>
@endsection

resources/views/users.blade.php
@extends("layouts.app")
@section("content")
<div class="container">
	
	<div class="row">
 <div class="table-responsive"> 
<table class="table">
	<thead>
		<tr>
			<th>Firstname</th>
			<th>Email</th>
			<th>Is Admin?</th>
			@if(Auth::user())
			<th>Action</th>
			@endif
		</tr>
	</thead>
	<tbody>
	@foreach($users as $user)
		<tr>
			<td>{{ $user->name }}</td> 
			<td>{{ $user->email }}</td>
			<td>{{ $user->is_admin? "Admin": "User" }}</td>
			@if(Auth::user())
			<td><a class="btn btn-warning" href="{{ route('users.edit', $user->id) }}">Edit</a></td>
			@endif
		</tr>
		@endforeach
	</tbody>
</table>
</div>
{{ $users->links() }}
</div>
</div>
@endsection